name: rise-environment
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - pydotplus
  - graphviz
  - python-graphviz
  - bokeh
  - rise
  - sqlalchemy
  - pymysql
  - seaborn
